name: Ensure public API changes are approved

permissions:
  pull-requests: read
  issues: read

on:
  issues:
    types: [labeled]

jobs:
  check-labels:
    runs-on: [ubuntu-latest]

    steps:
        - name: Get Token
          id: get_workflow_token
          uses: peter-murray/workflow-application-token-action@v2
          with:
            application_id: ${{ vars.APP_ID }}
            application_private_key: ${{ secrets.APP_KEY }}

        - name: Assign random api rewiewer to request
          uses: actions/github-script@v6
          with:
                github-token: ${{ steps.get_workflow_token.outputs.token }}
                script: |
                  // --------------------------------------------------------------------------------------------------------------------------------
                  //                                                       Constants
                  // --------------------------------------------------------------------------------------------------------------------------------                    
                  const TeamName = "api-review-team";
                  const ApiApprovedLabel = "api-approved";

                  core.notice(`Issue : ${JSON.stringify(context.payload.issue)}`);
                  
                  // --------------------------------------------------------------------------------------------------------------------------------
                  //                                                      Entry point
                  // --------------------------------------------------------------------------------------------------------------------------------                    
                  if (context.payload.issue.labels.findIndex(label => label.name === ApiApprovedLabel) === -1) {
                    core.notice(`Issue ${context.payload.issue.number} does not contain required label ${ApiApprovedLabel}. Ignoring`);
                  }
                  
                  const parameters = {
                    organization: "cecilifier",
                    teamToCheck: TeamName
                    };
                      
                  const query = `
                          query($organization: String!, $teamToCheck: String!) {
                            organization(login: $organization) { team(slug: $teamToCheck) { members { nodes { login } } } }
                          }`;
  
                  const teamMembers = await github.graphql(query, parameters);

                  for(const assignee of context.payload.issue.assignees) {
                    if (teamMembers.organization.team.members.nodes.indexOf(member => member.login === assignee.login)) {
                      core.notice(`Issue ${context.payload.issue.number} already assigned to api-review-team member ${assignee.login}`);
                      return;
                    }
                  }

                  const randonAssignee = teamMembers.organization.team.members.nodes[Math.floor(Math.random() * teamMembers.organization.team.members.nodes.length)];

                  core.notice(`Assigning issue ${context.payload.issue.number} to api-review-team member ${randonAssignee.login}...`);

                  core.notice(`-- Finished --`);