name: Ensure public API changes are approved

permissions:
  pull-requests: read
  issues: read

on:
  issues:
    types: [labeled]

jobs:
  check-labels:
    runs-on: [ubuntu-latest]
    #https://devopsjournal.io/blog/2022/01/03/GitHub-Tokens
    steps:
        - name: App Token
          uses: actions/create-github-app-token@v1
          id: app-token
          with:
            app_id: ${{ vars.APP_ID }}
            private_key: ${{ secrets.APP_KEY }}
        - name: Assign random api rewiewer to request
          uses: actions/github-script@v6
          with:
                github-token: ${{ steps.app-token.outputs.token }}
                script: |
                  // --------------------------------------------------------------------------------------------------------------------------------
                  //                                                       Constants
                  // --------------------------------------------------------------------------------------------------------------------------------                    
                  const TeamName = "api-review-team";
                  const ApiApprovedLabel = "api-approved";

                  core.notice(`Issue : ${JSON.stringify(context.payload)}`);
                  
                  // --------------------------------------------------------------------------------------------------------------------------------
                  //                                                      Entry point
                  // --------------------------------------------------------------------------------------------------------------------------------                    
                  if (context.payload.issue.labels.findIndex(label => label.name === ApiApprovedLabel) === -1) {
                    core.notice(`Issue ${context.payload.issue.number} does not contain required label ${ApiApprovedLabel}. Ignoring`);
                    return;
                  }

                  const owner = context.repo.owner;
                  const repo = context.repo.repo;
                  const number = context.payload.issue.number;
                  const assignees = context.payload.issue.assignees;

                  const parameters = {
                    organization: "cecilifier",
                    teamToCheck: TeamName
                    };
                      
                  const query = `
                          query($organization: String!, $teamToCheck: String!) {
                            organization(login: $organization) { team(slug: $teamToCheck) { members { nodes { login } } } }
                          }`;
  
                  const teamMembers = await github.graphql(query, parameters);
                  for(const assignee of assignees) {
                    if (teamMembers.organization.team.members.nodes.indexOf(member => member.login === assignee.login)) {
                      core.notice(`Issue ${number} already assigned to api-review-team member ${assignee.login}`);
                      return;
                    }
                  }

                  const randomAssignee = teamMembers.organization.team.members.nodes[Math.floor(Math.random() * teamMembers.organization.team.members.nodes.length)];

                  core.notice(`Assigning issue ${number} to api-review-team member ${randomAssignee.login}...`);

                  await github.rest.issues.addAssignees({
                    owner,
                    repo,
                    issue_number: number,
                    assignees: [randomAssignee.login],
                  });

                  core.notice(`-- Finished --`);