name: Ensure public API changes are approved

permissions:
  pull-requests: read
  issues: read

on:
  issues:
    types: [labeled, unlabeled]

jobs:
  check-labels:
    runs-on: [ubuntu-latest]

    steps:
        - name: Check 'api-approved' label
          uses: actions/github-script@v6
          with:
                github-token: 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
                script: |
                    // --------------------------------------------------------------------------------------------------------------------------------
                    //                                                      Entry point
                    // --------------------------------------------------------------------------------------------------------------------------------                   
                    core.notice(`Issue : ${JSON.stringify(context.payload.issue)}`);

                    const parameters = {
                        organization: context.payload.organization.login,
                        teamToCheck: "ads-sdk-gateway-working-group"
                      };
                      
                      const query = `
                            query($organization: String!, $teamToCheck: String!) {
                                organization(login: $organization) { team(slug: $teamToCheck) { members { nodes { login } } } }
                            }`;
  
                      const teamMembers = await github.graphql(query, parameters);
                      core.notice(`Checking if ${login} is memebr of api-review-team\n\n${JSON.stringify(teamMembers)}`);

                      for(let member of teamMembers.organization.team.members.nodes)
                      {
                         core.notice(`Member loging: ${member.login}`);
                      }

                    core.notice(`Approver name 2: ${approverName}`);

